### PR TITLE
Api improvements and monorepo

### PR DESCRIPTION
**Pull request by zwilling**
This PR:

- Introduces a snap-api package that FrontEnds can import so use the snap in a simple way
- Separates common types used in snap, api and zkKYC into another package
- Moves zkKYC into this repo to create a monorepo for all Galactica zkKYC packages. This simplifies handling the full software stack together and synchronize future changes over all packages. There are a lot of changes in this package after moving to make it consistent with eslint. That was great because it found some errors with static analysis.
- Adjusted snap and example front-ends according to the new API and type packages

### CODE REVIEW

**Comment by zwilling** [comment]
After merging we should update https://docs.galactica.com/galactica-developer-documentation/building-a-galactica-dapp/front-end/galactica-snap-json-rpc-api

**Comment by zwilling** [comment]
Finally, the pipeline works as well. Now the PR can be reviewed.
@anhdungle93 Could you please check the changes in the snap package? It would also be good if you can review the changes in teh zk-certificate package. It changed a bit because we moved it here. I moved the repo here with these changes: https://github.com/Galactica-corp/zkKYC/compare/main...monorepoChanges
The following changes are in this PR, including linting for consistent code style and some build modifications to make it work in the monorepo. The ZK circuits and scripts should work fine. They are only excluded in the pipeline for now because I first have to speed up the process and adjust unittest timeouts.

@alex-abanin Can you please review the snap-api and galactica-type packages of this PR? Feel free to also check the two front-end examples, but in my opinion they are not essential.

If you both accept the PR, we can merge it.

**Comment by anhdungle93** [comment]
It looks good for me, because it seems like in the zk-certificate package the only change was in the import path of certain libraries.

**Comment by alex-abanin** [comment]
when I try to install `@galactica-net/snap-api`

`pnpm i @galactica-net/snap-api `
I get an error:  `ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@galactica-net/galactica-types@workspace:^" is in the dependencies but no package named "@galactica-net/galactica-types" is present in the workspace`

It happens because published `@galactica-net/snap-api` has dependency `@galactica-net/galactica-types: "workspace ^"`, but it's not correct. There is no `workspace` there after publishing.

**Comment by zwilling** [comment]
> when I try to install `@galactica-net/snap-api`
> 
> `pnpm i @galactica-net/snap-api ` I get an error:  `ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@galactica-net/galactica-types@workspace:^" is in the dependencies but no package named "@galactica-net/galactica-types" is present in the workspace`
> 
> It happens because published `@galactica-net/snap-api` has dependency `@galactica-net/galactica-types: "workspace ^"`, but it's not correct. There is no `workspace` there after publishing.

Thanks for finding this. I republished the packages with correct dependencies and modified the README instructions about how to do that.

**Review by anhdungle93 — APPROVED** [review]

**Pull request merged**
