### PR TITLE
Guardian registry improvements

### PR DESCRIPTION
**Pull request by zwilling**
Extended Guardian registry
- Contains public EdDSA key used for signing zkCerts
- Name to identify entries in frontend and explorer in a human readable way
- reverse mapping from pubkey to address to find out what provider signed a zkCert

### CODE REVIEW

**Comment by zwilling** [comment]
Waiting for https://github.com/Galactica-corp/galactica-monorepo/pull/19 to be merged first.

**Comment by zwilling** [comment]
This PR is ready to be reviewed now @anhdungle93 
Besides the points mentioned above, the changes also include:
- Renaming of `KYCCenter*` contracts to `Guardian*` to reflect  it not being limited to KYC
- Refactoring of the deployment scripts to deploy everything at once without duplicating code.

**Comment by anhdungle93** [comment]
Everything looks good, but since guardians cannot change name, one option can be to store the Guardian name along with the SBTs cached in local storage, so we don't have to lookup onchain everytime user opens the frontend.

**Comment by zwilling** [comment]
> Everything looks good, but since guardians cannot change name, one option can be to store the Guardian name along with the SBTs cached in local storage, so we don't have to lookup onchain everytime user opens the frontend?

@anhdungle93 
The guardian name can change if the same address gets whitelisted again with 
```
    function grantGuardianRole(
        address guardian,
        uint256[2] calldata pubKey,
        string calldata name
    ) public onlyOwner {
        guardians[guardian].whitelisted = true;
        guardians[guardian].pubKey = pubKey;
        guardians[guardian].name = name;

        pubKeyToAddress[pubKey[0]][pubKey[1]] = guardian;
    }
    ```

**Pull request merged**
